/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cyhserver2;

import Logica.Clases;
import Logica.Cronica;
import Logica.Enemigo;
import Logica.Habilidad;
import Logica.NieblasTerritorios;
import Logica.Personaje;
import Logica.Posiciones;
import Logica.StackObjeto;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mmancora
 */
public class VentanaPrincipal extends javax.swing.JFrame implements Runnable {

    Cronica cronica;
    public VentanaPrincipal() {
        initComponents();
        
        Thread hilo = new Thread(this);
        hilo.start();
        
        ArrayList<Enemigo> enemigos = new ArrayList();
        enemigos.add(new Enemigo("Wargo1",10,6,5,6,1,2,1,Posiciones.O2,10,0,"piel_de_wargo.png"));
        ArrayList<Personaje> personajes = new ArrayList();
        personajes.add(new Personaje(1,"Anaxímenes", Clases.COMBATIENTE,13,5,4,5,1,2,2,Posiciones.NE2,"emblema_combatiente.png"));
        personajes.add(new Personaje(2,"Caztiel",Clases.ACROBATA,16,2,4,2,7,1,2,Posiciones.N,"emblema_acrobata.png"));
        personajes.add(new Personaje(3,"Eilien",Clases.GUARDIA,16,2,4,2,7,1,2,Posiciones.N2,"emblema_guardia.png"));
        personajes.add(new Personaje(4,"Luna",Clases.ESTRATEGA,16,2,4,2,7,1,2,Posiciones.C,"emblema_estratega.png"));
        
        cronica = new Cronica(personajes, enemigos, NieblasTerritorios.CODIGOBLANCO, NieblasTerritorios.TERRITORIO_BOSQUENEGRO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaLog = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaLog.setColumns(20);
        areaLog.setRows(5);
        jScrollPane1.setViewportView(areaLog);

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.areaLog.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaLog;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        int port = 2000;
        try {
            ServerSocket server = new ServerSocket(port);
            areaLog.append("Conexión establecida (puerto: "+port+")\n");
            while(true){
                Socket socket = server.accept();
                DataInputStream entrada = new DataInputStream(socket.getInputStream());
                String mensaje = entrada.readUTF();
                areaLog.append("Personaje 1 pide Crónica inicial.\n");
                enviarCronica();
                
            }
            
        } catch (IOException ex) {
            areaLog.append("Servidor sin construir/n");
        }
        
    }
    
    public void enviarCronica(){
        Socket socket;
        try {
            socket = new Socket("192.168.1.83",2000);
            ObjectOutputStream salida = new ObjectOutputStream(socket.getOutputStream());
            salida.writeObject(cronica);
            areaLog.append("Se envia la crónica inicial al personaje 1.\n");
            socket.close();
        } catch (IOException ex) {
            areaLog.append("No se pudo enviar la cronica al personaje1.\n");
        }
        
    }
}
